apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
        - name: web
          image: singymingy86/testui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          # env:
          # - name: REACT_APP_TODO_APP_API_ENDPOINT
          #   value: "api.default.svc.cluster.local/api"
          